version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region <your region> | docker login --username AWS --password-stdin ************ your ecr
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t <image name> ./Docker/nginx/
      - docker tag <image name>:latest your ecr/<image name>:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to ECR...
      - docker push <your ecr>/<image name>:latest
